Here we will implement the political optimizer algorithm. 
It consists of 4 steps: 

- The main framework (algorithm 1 in the paper)
- The Election Campaign (algorithm 2)
- Party Switching (algorithm 3)
- Parliamentary Affairs (algorithm 4)

For the moment, we can just make this 4 functions in a jupyter notebook. When we have confirmation from the mealpy library, we can start adapting it to the form they want. (they have an optimizer class with some built-in methods etc.)

A first problem is how we want to initialise the population. From the matlab code of the authors, this is how they did it: https://fr.mathworks.com/matlabcentral/fileexchange/74577-political-optimizer-po/
Again, if we can work within the MealPy library, there are built-in functions for this. I will therefore try to make abstraction of this for now. 

In [1]:
import numpy as np

In [3]:
# TODO: Check that everything is right, but it runs

def ElectionCampaign(fun, d, pji, pjitminus1, pstari, cstarj):
    if(fun(pji) <= fun(pjitminus1)):
        for k in range(d):
            mstar = pstari[k]
            r = np.random.rand()
            # Implementation of eq9
            if((pjitminus1[k] <= pji[k] <= mstar) or (pjitminus1[k] >= pji[k] >= mstar)):
                pji[k] = mstar + r*(mstar - pji[k])
            elif((pjitminus1[k] <= mstar <= pji[k]) or (pjitminus1[k] >= mstar >= pji[k])):
                pji[k] = mstar = (2*r-1)*abs(mstar - pji[k])
            elif((mstar <= pjitminus1[k] <= pji[k]) or (mstar >= pjitminus1[k] >= pji[k])):
                pji[k] = mstar + (2*r-1)* abs(mstar - pjitminus1[k])
            mstar = cstarj[k]
            r = np.random.rand()
            # This is just a copy paste of what was above, since eq 9 already implemented
            if((pjitminus1[k] <= pji[k] <= mstar) or (pjitminus1[k] >= pji[k] >= mstar)):
                pji[k] = mstar + r*(mstar - pji[k])
            elif((pjitminus1[k] <= mstar <= pji[k]) or (pjitminus1[k] >= mstar >= pji[k])):
                pji[k] = mstar = (2*r-1)*abs(mstar - pji[k])
            elif((mstar <= pjitminus1[k] <= pji[k]) or (mstar >= pjitminus1[k] >= pji[k])):
                pji[k] = mstar + (2*r-1)* abs(mstar - pjitminus1[k])
    else:
        for k in range(d):
            mstar = pstari[k]
            r = np.random.rand()
            # Implementation of eq 10
            if((pjitminus1[k] <= pji[k] <= mstar) or (pjitminus1[k] >= pji[k] >= mstar)):
                pji[k] = mstar + (2*r-1)*abs(mstar - pji[k])
            elif((pjitminus1[k] <= mstar <= pji[k]) or (pjitminus1[k] >= mstar >= pji[k])):
                pji[k] = pjitminus1[k] + r*(pji[k] - pjitminus1[k])
            elif((mstar <= pjitminus1[k] <= pji[k]) or (mstar >= pjitminus1[k] >= pji[k])):
                pji[k] = mstar + (2*r - 1) * abs(mstar - pjitminus1[k])
            mstar = cstarj[k]
            r = np.random.rand()
            # Copy paste of what was above, since eq 10 already implemented
            if((pjitminus1[k] <= pji[k] <= mstar) or (pjitminus1[k] >= pji[k] >= mstar)):
                pji[k] = mstar + (2*r-1)*abs(mstar - pji[k])
            elif((pjitminus1[k] <= mstar <= pji[k]) or (pjitminus1[k] >= mstar >= pji[k])):
                pji[k] = pjitminus1[k] + r*(pji[k] - pjitminus1[k])
            elif((mstar <= pjitminus1[k] <= pji[k]) or (mstar >= pjitminus1[k] >= pji[k])):
                pji[k] = mstar + (2*r - 1) * abs(mstar - pjitminus1[k])
    return pji

In [41]:
def PartySwitching(parties, population, Lambda, fitnesst, n):
    for i in range(len(parties)): 
        #got the ith party
            for j in range(len(parties[i])):
                #for each member of the party
                sp = np.random.rand()
                if(sp < Lambda):
                    r = np.random.randint(0,n-1) #the random new party (from 0 to n-1 as it how python indexes)
                    q = np.argmax(fitnesst[parties[r]]) #do we have to recompute here? or time consuming
                    old = parties[i][j].copy()
                    new = parties[r][q].copy()
                    # print('before')
                    # print(parties[i])
                    # print(parties[r])
                    #we swap :
                    parties[i][j] = new
                    parties[r][q] = old
                    # print('after')
                    # print(parties[i])
                    # print(parties[r])
                    # Determine q with eq11
                    # swap pqr and pji
    return parties

In [5]:
def ParliamentaryAffairs(constituencyLeaders, population,n):
    for j in range(n):
        r = np.random.randint(0,n)
        a = np.random.rand(0)
        
    return 0

In [44]:
def PoliticalOptimizer(fun, n, lambdamax, tmax, d):
    '''
    Parameters: 
    fun -> the function we want to optimize
    n -> the number of contituencies, political parties and party members
    lambdamax -> upper limit of the party switching rate
    tmax -> number of iterations
    
    d -> number of dimensions, we don't want this to be a parameter later I think
    
    Out: the final population

    '''
    
    ################
    # Initialization: sth arbitrary now to replicate the paper, making 9 2D individuals
    # n = 3 parties, d = 2 dimensions
    ################
    
    populationt = np.zeros((n**2, d))
    for i in range(n**2):
        populationt[i,:] = np.random.normal(0,1,2)
    print(populationt) 
    ###############
    # Initializing parties
    # We have n parties and constituencies in the political system, we initialize them here
    # party 1 consists of the first n individuals, party 2 of the following n etc.
    # we store the indices in parties, so that we can always use the indices to refer to individuals in the population
    ###############
    parties = constituencies = np.array([range(n*i, (n*i+n)) for i in range(n)])
    print(f'The parties: {parties}')
    
    ###############
    # Initialize the fitness of all individuals
    ###############
    fitnesst = np.array([fun(x) for x in populationt])    
    print(f'Their fitness: {fitnesst}')
    ################# 
    # Computing the party leaders
    #################
    
    # First we look at the first party, then the second, then the third,...
    
    n_party = 0
    party_leaders = np.zeros(n)
    for party in parties:
        party_leaders[n_party] = n_party*n + np.argmin(fitnesst[party])
        # 0 * 3 + 0,1 or 2. Then 1*3 + 0,1,2
        n_party += 1
        
    #print(f'The selected party leaders: {party_leaders}')
    
    ################
    # Computing the constituency leaders, 1 member for each party competes against each other
    # So in our toy example it is individual 0 vs. 3 vs. 6
    # In general it is 0 * n, 1 * n ...
    ################
    
    # first we make the constituencies
    constituencies = []
    
    for const in range(n):
        constituency = []
        for party in parties: 
            constituency.append(party[const])
        constituencies.append(constituency)
    # then we select the leader
    n_constituency = 0
    constituency_leaders = np.zeros(n)
    for constituency in constituencies: 
        # For constituency 0: 0, 3 or 6
        # For constituency 1: 1, 4 or 7
        constituency_leaders[n_constituency] = n_constituency + 3*np.argmin(fitnesst[constituency])
        n_constituency += 1

    print(f'The constituency leaders: {constituency_leaders}')
    
    ################
    # Further initialisations
    ################
    t = 1
    populationtmin1 = populationt
    fitnesstmin1 = fitnesst
    Lambda = lambdamax
    print(f'index of p00 is: {parties[0][0]}')
    print(f'individual p00 is: {populationt[parties[0,0]]}')
    
    ################
    # Starting while loop
    ################
    while(t <= tmax):
        populationtemp = populationt
        fitnesstemp = fitnesst
        for i in range(len(parties)): 
            for j in range(len(party)):
                # partyleaders and constituency leaders give the index of the party leader
                # we can plug this into the population to get the party leader
                populationt[parties[i,j]] = print(ElectionCampaign(fun,d, pji = populationt[parties[i,j]], pjitminus1 = populationtmin1[parties[i,j]], pstari = populationt[int(party_leaders[i])], cstarj = populationt[int(constituency_leaders[j])]))
        parties = PartySwitching(parties, populationt, Lambda, fitnesst, n)
                  
        t += 1
    
# here we try to minimize the 3D-paraboloïd with center 0        
PoliticalOptimizer(lambda x: x[0]**2 + x[1]**2,3,2,2,2) 

[[ 1.01567523  0.22322097]
 [ 0.31731872 -2.0320235 ]
 [ 0.94887886  0.21612362]
 [-0.7836726  -0.48956257]
 [ 0.15957534 -0.28127606]
 [-0.07600374  0.90048651]
 [-0.22408457  0.68107948]
 [-0.67676127  0.14084535]
 [ 1.03522012 -1.90219331]]
The parties: [[0 1 2]
 [3 4 5]
 [6 7 8]]
Their fitness: [1.08142377 4.22981065 0.9470805  0.85381425 0.10458051 0.81665251
 0.51408316 0.47784322 4.6900201 ]
The constituency leaders: [6. 4. 5.]
index of p00 is: 0
individual p00 is: [1.01567523 0.22322097]
[-1.12401755  0.85524259]
[-0.89717102 -0.33587628]
[-0.15301266  1.48373331]
[-0.61281625  1.02390447]
[ 0.15957534 -0.28127606]
[-0.07600374  0.90048651]
[-0.98517264 -0.31343125]
[-0.67676127  0.14084535]
[ 1.03522012 -1.90219331]
before
[0 1 2]
[0 1 2]
after
[1 0 2]
[1 0 2]
before
[1 0 2]
[3 4 5]
after
[1 3 2]
[0 4 5]
before
[1 3 2]
[1 3 2]
after
[2 3 1]
[2 3 1]
before
[0 4 5]
[0 4 5]
after
[0 4 5]
[0 4 5]
before
[0 4 5]
[2 3 1]
after
[0 1 5]
[2 3 4]
before
[0 1 5]
[0 1 5]
after
[0 5 1]
[0 